package models

import (
	"crypto/rand"
	"fmt"
	"regexp"
	"strings"
	"time"
)

// =============================================================================
// Backups
// =============================================================================

// BackupStatus is the lifecycle state of a backup.
type BackupStatus string

const (
	BackupStatusPending   BackupStatus = "pending"
	BackupStatusRunning   BackupStatus = "running"
	BackupStatusAvailable BackupStatus = "available"
	BackupStatusFailed    BackupStatus = "failed"
)

// BackupType records what caused the backup to be taken.
type BackupType string

const (
	BackupTypeManual    BackupType = "manual"
	BackupTypeAutomated BackupType = "automated"
	// BackupTypePreRestore is taken automatically before a restore overwrites
	// a database, so a mistaken restore is itself recoverable.
	BackupTypePreRestore BackupType = "pre-restore"
)

// Backup is a logical dump of one database instance.
//
// Tefter takes logical backups (pg_dump / mysqldump) rather than filesystem
// snapshots: they are portable across engine versions and can be restored into
// a differently sized instance, which is what a self-hosted platform actually
// needs. The trade is that they are slower on very large databases.
type Backup struct {
	ID       string `json:"id"`
	Instance string `json:"instance"`
	// InstanceUID is the stable identity of the instance this backup was taken
	// from (see DBInstance.UID). It distinguishes a backup of the current
	// instance from a backup of an earlier, since deleted instance that reused
	// the same name. Empty on backups taken before this field existed.
	InstanceUID string `json:"instance_uid,omitempty"`
	Engine      Engine `json:"engine"`
	Database    string `json:"database"`

	// FromDeletedInstance is set when listing backups: true when no instance
	// with this backup's identity currently exists. It is computed, not
	// stored, so the dashboard can flag a backup that no longer has a live
	// instance behind it.
	FromDeletedInstance bool `json:"from_deleted_instance,omitempty"`

	Status BackupStatus `json:"status"`
	Type   BackupType   `json:"type"`

	// Description is a free-text note from whoever took the backup. Backup ids
	// are timestamps, which say when but never why, and "why" is what someone
	// picking a restore point actually needs.
	Description string `json:"description,omitempty"`

	SizeBytes int64  `json:"size_bytes"`
	Path      string `json:"path,omitempty"`

	StartedAt   time.Time  `json:"started_at"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	// DurationSeconds is how long the dump took, useful for sizing a backup
	// window.
	DurationSeconds float64 `json:"duration_seconds,omitempty"`

	Error string `json:"error,omitempty"`
}

// backupIDRe constrains a backup id. Ids are generated by Tefter, but they
// arrive back as path parameters and are used to build a filesystem path, so
// they are validated on the way in rather than trusted.
var backupIDRe = regexp.MustCompile(`^[a-z0-9][a-z0-9-]{0,80}$`)

// IsValidBackupID reports whether an id is safe to use in a path.
func IsValidBackupID(id string) bool {
	return backupIDRe.MatchString(id)
}

// NewBackupID builds a sortable, human-readable backup id.
//
// Prefixing with the instance and a UTC timestamp means a directory listing is
// chronological per instance without needing to read any metadata.
func NewBackupID(instance string, at time.Time) string {
	// The timestamp alone is not unique: it has one-second resolution, and two
	// backups of one instance inside the same second are entirely normal (a
	// restore takes a pre-restore backup immediately before reading the backup
	// it was asked to restore). When that collided, the second backup wrote
	// over the first one's file, so the restore replayed the state it had just
	// been asked to roll back. The suffix makes ids collision-proof; a
	// sortable timestamp still leads so ids order naturally.
	return fmt.Sprintf("%s-%s-%s", instance, at.UTC().Format("20060102-150405"), randomSuffix())
}

// randomSuffix returns four lowercase alphanumerics.
func randomSuffix() string {
	const alphabet = "abcdefghijklmnopqrstuvwxyz0123456789"
	b := make([]byte, 4)
	if _, err := rand.Read(b); err != nil {
		// Only reachable if the system entropy source is broken. Continuing
		// would risk silently overwriting a backup, so stop instead.
		panic("tefter: cannot read random bytes for a backup id: " + err.Error())
	}
	for i := range b {
		b[i] = alphabet[int(b[i])%len(alphabet)]
	}
	return string(b)
}

// =============================================================================
// Requests
// =============================================================================

// CreateBackupRequest takes a backup of an instance.
type CreateBackupRequest struct {
	// Type defaults to manual.
	Type BackupType `json:"type,omitempty"`

	// Description is an optional note stored with the backup.
	Description string `json:"description,omitempty"`
}

// maxBackupDescription bounds the note so a caller cannot use it to write an
// arbitrarily large file into the backup directory.
const maxBackupDescription = 500

// Validate checks the request and fills in defaults.
func (r *CreateBackupRequest) Validate() error {
	if r.Type == "" {
		r.Type = BackupTypeManual
	}
	switch r.Type {
	case BackupTypeManual, BackupTypeAutomated, BackupTypePreRestore:
	default:
		return &ValidationError{
			Field:   "type",
			Message: "type must be one of: manual, automated, pre-restore",
		}
	}

	r.Description = strings.TrimSpace(r.Description)
	if len(r.Description) > maxBackupDescription {
		return &ValidationError{
			Field:   "description",
			Message: fmt.Sprintf("description must be at most %d characters", maxBackupDescription),
		}
	}
	return nil
}

// RestoreBackupRequest restores a backup into an instance.
type RestoreBackupRequest struct {
	// BackupID identifies the backup to restore.
	BackupID string `json:"backup_id"`

	// TargetInstance is where to restore. Empty restores into the instance the
	// backup came from.
	TargetInstance string `json:"target_instance,omitempty"`

	// Confirm must be true. A restore overwrites live data, so it cannot be
	// triggered by a request that merely names a backup.
	Confirm bool `json:"confirm"`

	// SkipPreRestoreBackup disables the safety backup taken before the
	// overwrite. Off by default because that backup is the only way back.
	SkipPreRestoreBackup bool `json:"skip_pre_restore_backup,omitempty"`

	// AllowDifferentInstance must be set to restore a backup into an instance
	// that is not the one it was taken from. This covers two cases that look
	// identical to a name-based check but are not: restoring into a
	// deliberately different instance, and restoring an old backup into a new
	// instance that reuses a deleted instance's name. Both overwrite data that
	// did not come from that backup, so both require this explicit opt-in.
	AllowDifferentInstance bool `json:"allow_different_instance,omitempty"`
}

// Validate checks the request.
func (r *RestoreBackupRequest) Validate() error {
	r.BackupID = strings.TrimSpace(r.BackupID)
	if r.BackupID == "" {
		return &ValidationError{Field: "backup_id", Message: "backup_id is required"}
	}
	if !IsValidBackupID(r.BackupID) {
		return &ValidationError{Field: "backup_id", Message: "malformed backup id"}
	}
	if !r.Confirm {
		return &ValidationError{
			Field:   "confirm",
			Message: "a restore overwrites the target database; set confirm to true to proceed",
		}
	}
	return nil
}

// RestoreResult reports the outcome of a restore.
type RestoreResult struct {
	BackupID        string  `json:"backup_id"`
	TargetInstance  string  `json:"target_instance"`
	Restored        bool    `json:"restored"`
	DurationSeconds float64 `json:"duration_seconds"`
	// PreRestoreBackupID names the safety backup taken first, when one was.
	PreRestoreBackupID string `json:"pre_restore_backup_id,omitempty"`
}
